spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1221e876540cca8ae5f9
            client-secret: 162a98e9e71b29606a3c5f8e5e66a78e7b6a50e5
            authorization-grant-type: authorization_code
            client-name: github
          gitee:
            client-id: 6117b6e01c09e53cd5b28c04492e1bb7c8eb33c343492e69f599160b464ef971
            client-secret: bf1d6812ee3f1e97f2f87e49d4d39224247e9c3ebbaac2bbf089b22140dfdd72
            authorization-grant-type: authorization_code
            client-name: gitee
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/identity_server
    username: root
    password: wangle
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 50000
      max-lifetime: 55000
      maximum-pool-size: 100
      minimum-idle: 50

