spring:
  security:
    oauth2:
      client:
        registration:
          autism-client-client-credentials:
            provider: autism
            client-name: autism-client-client-credentials
            client-id: f62ac251-36d7-42c8-9f75-c31c90111bd4
            client-secret: secret
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope: message.read,message.write
          silent-client-client-credentials-jwt:
            provider: silent
            client-name: silent-client-client-credentials-jwt
            client-id: 8a349006-b8e3-427b-8814-bc4b32e8930a
            # HmacSHA256 The secret length must be at least 256 bits
            client-secret: 0c1501f4a8a35db0a725d1f547f5466f
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_jwt
            scope: message.read,message.write
          quietly-client-client-credentials-jwt-private-key:
            provider: quietly
            client-name: quietly-client-client-credentials-jwt-private-key
            client-id: b3d64549-0c6b-4306-9170-886dd8652704
            authorization-grant-type: client_credentials
            client-authentication-method: private_key_jwt
            scope: message.read,message.write
        provider:
          autism:
            authorization-uri: http://armorauth-server:9000/oauth2/authorize
            token-uri: http://armorauth-server:9000/oauth2/token
          silent:
            authorization-uri: http://armorauth-server:9000/oauth2/authorize
            token-uri: http://armorauth-server:9000/oauth2/token
            jwk-set-uri: http://armorauth-server:9000/oauth2/jwks
          quietly:
            authorization-uri: http://armorauth-server:9000/oauth2/authorize
            token-uri: http://armorauth-server:9000/oauth2/token
            jwk-set-uri: http://armorauth-server:9000/oauth2/jwks

